# Generated by Django 5.2.7 on 2025-10-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_integration', '0004_personal_trainer_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
    ]
